config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create]
  root 'pages#index'
  resources :user_sessions, only: [:new, :create] do
    get :destroy
    collection do
      get :log_in
    end
  end

  resources :products

  resources :product_baskets, only: [:new, :create] do
    get :product_basket_delete

  end

  resources :basket, only: [:index, :new, :create,:edit,:update]do

  end

  resources :users, only: [:index, :new, :create] do

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :product_baskets
  validates_uniqueness_of :user_id
  validates_presence_of :user_id

end

app/models/product.rb
class Product < ApplicationRecord
  validates_uniqueness_of :product_code
  validates_presence_of :name
  validates_presence_of :product_code
end

app/models/product_basket.rb
class ProductBasket < ApplicationRecord
  belongs_to :product
  belongs_to :basket
  validates_presence_of :product_id
  validates_presence_of :basket_id
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :password, validations: true
  validates_uniqueness_of :name
  validates_presence_of :name
  as_enum :role, { client: 0, admin: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController

  def edit
    @basket = Basket.find(params[:id])
    if params[:amount].to_i > 0
      product_basket = ProductBasket.find_or_create_by(basket_id:@basket.id,product_id:params[:product_id])
      BasketDomain.calculate_total_prize(product_basket,params[:amount].to_i)
    end
    redirect_to users_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/product_baskets_controller.rb
class ProductBasketsController < ApplicationController

  def product_basket_delete

    @product_basket = ProductBasket.find_by_id(params[:product_basket_id].to_i)
    @product_basket.basket.update(total_prize:BasketDomain.remove_product_amount(@product_basket))
    @product_basket.destroy
    redirect_to users_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    Product.create(name:params[:product][:name],prize:params[:product][:prize],product_code:ProductDomain.generate_product_code(params[:product][:name]))
    redirect_to users_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end


  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      @product = Product.new
      @product_baskets = ProductBasket.left_joins(:basket).where(baskets:{user_id: current_user.id})
      @basket = Basket.find_by_user_id(current_user.id)
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      Basket.create(user_id: @user.id)
      redirect_to users_path
    else
      flash[:alert] = "Incorrect passwords"
      render 'user_sessions/new'
    end
  end

  def home

  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_baskets_helper.rb
module ProductBasketsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashregister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.slim
html class="text-center pt-1 mb-5 pb-1"
  head
    title = 'Cash Register'
  body
    h1 = 'Cash Register'
    row
      col
        p = 'App that register your products in basket'
    div
      = link_to "Log In", log_in_user_sessions_path,   class: "btn btn-primary"

    div = link_to 'Register',  new_user_session_path


    // añadir enter to secret page => tap beer show

app/views/user_sessions/log_in.html.slim
html class="text-center pt-1 mb-5 pb-1"
  head
    title = 'Cash Register'
  body
    .div  class="form-outline mb-4"
      h1 = 'Cash Register'
    .div class="form-outline mb-4"
      = link_to root_path, class: "btn btn-primary"
        i.fa.fa-home.btn-xs
    row
      col
        div = form_for :user, url:user_sessions_path , method:'POST', html: { multipart: true }, authenticity_token: true, remote: true do |f|

          .div  class="form-outline mb-4"
            - title = 'Username'
            = f.text_field :name,  placeholder: title, title: title, required: true

          .div  class="form-outline mb-4"
            - title = 'Password'
            = f.password_field :password, placeholder: title, title: title, required: true

          .div  class="form-outline mb-4"
            = f.submit 'Enter', class: 'btn btn-primary'

app/views/user_sessions/new.html.slim
html class="text-center pt-1 mb-5 pb-1"

  head
    title = 'Cash Register'

  body
    .div  class="form-outline mb-4"
      h1 = 'Cash Register'
    .div class="form-outline mb-4"
      = link_to  root_path, class: "btn btn-primary"
        i.fa.fa-home.btn-xs


    row
      col
        div = form_for @user, html: { multipart: true }, authenticity_token: true, remote: true do |f|

          - flash.each do |type, msg|
            div class="alert alert-warning"
              = msg

          .div  class="form-outline mb-4"
            - title = 'Username'
            = f.text_field :name,  placeholder: title, title: title, required: true

          .div  class="form-outline mb-4"
            - title = 'Password'
            = f.password_field :password, placeholder: title, title: title, required: true

          .div  class="form-outline mb-4"
            - title = 'Password confirmation'
            = f.password_field :password_confirmation, placeholder: title, title: title, required: true

          .div  class="form-outline mb-4"
            = f.submit 'Create', class: 'btn btn-primary'

app/views/users/index.html.slim
h1 class="text-center pt-1 mb-5 pb-1" = 'Cash Register'
h3 class="text-center pt-1 mb-5 pb-1" = 'Product'
- if current_user.role_cd == User.roles[:admin]
  div class="text-center pt-1 mb-5 pb-1" = form_for @product , method:'POST', html: { multipart: true }, authenticity_token: true, remote: true do |f|

    .div  class="form-outline mb-4"
      - title = 'Name'
      = f.text_field :name,  placeholder: title, title: title, required: true
    .div class="form-outline mb-4"
      - title = 'Prize'
      = f.number_field :prize, placeholder: title, title: title, required: true

    .div  class="form-outline mb-4"
      = f.submit 'Add Product', class: 'btn btn-primary'
h3 class="text-center pt-1 mb-5 pb-1"
  = 'Products list'
div class="form-outline mb-4" style="overflow: auto; height: 300px;"

  table class="table table-striped table-bordered"
    thead
      tr
        th = "Code"
        th = "Name"
        th = "Prize"
        th = "Amount"
        th = "Actions"

    tbody
      - Product.all.try(:each) do |product|
        tr
          td = product.try(:product_code)
          td = product.try(:name)
          td = product.try(:prize)
          div = form_for @basket, url: edit_basket_path(@basket.id),method:'GET', html: { multipart: true }, authenticity_token: true, remote: true do |f|
            = hidden_field_tag :product_id, product.id
            td = number_field_tag :amount,  ProductBasket.where(basket_id:@basket.id,product_id:product.id).take.try(:amount), min:0, step: 1,id:'amount_of_product_'+product.id.to_s
            td = button_tag type: :submit, class: 'btn btn-primary', title: "Add to basket" do
                 = fa_icon 'plus'

h3 class="text-center pt-1 mb-5 pb-1"
  = "Basket List "
  = fa_icon 'opencart'

div  style="overflow: auto; height: 300px;"

  table class="table table-striped table-bordered"
    thead
      tr
        th = "Products"
        th = "Prize"
        th = "Amount"
        th = "Actions"


    tbody
      - @product_baskets.try(:each) do |product_basket|
        tr
          td = product_basket.product.name
          td = BasketDomain.amount_prize(product_basket)
          td = product_basket.amount
          td = link_to product_basket_product_basket_delete_path(product_basket.id),  title: 'Remove product from the basket' do
               i.fa.fa-trash.btn-xs
  div class="card"
    div class="card-body"
      h5 = 'Total prize: '+@basket.total_prize.to_s+'€'
div
  = link_to 'Log Out', user_session_destroy_path(current_user), class: 'btn btn-primary'